spring:
#  datasource:
#    hikari:
#      username:
#      password:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://.com:3306/order_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
  application:
      name: order-server

server:
  port: 1003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka/
  instance:
    hostname: 172.0.0.1
