spring:
  application:
    name: eureka-server
  profiles:
    active: dev2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka,http://localhost:8767/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: 172.0.0.1
