spring:
  application:
    name: hello-server
  profiles:
    active: dev2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka/,http://localhost:8767/eureka/
  instance:
    hostname: 172.0.0.1
